project:
  type: website

website:
  image: picture.png
  title: "Port"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects/index.qmd
        text: Projects
      - about.qmd

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true



